export const GET_SONGS = 'ADD_SONG';
export const CURRENT_SONG = 'CURRENT_SONG';
export const SET_NEW_CURRENT_SONG = 'SET_NEW_CURRENT_SONG';
export const SKIP_SONG_FORWARD = 'SKIP_SONG_FORWARD';
export const SKIP_SONG_BACKWARD = 'SKIP_SONG_BACKWARD';